scalar DateTime
scalar Currency

type AddressV2 {
  city: String
  country: String
  country_iso2: String
  company: String
  email: String
  first_name: String
  last_name: String
  phone: String
  state: String
  street_1: String
  street_2: String
  zip: String!
}

# BigCommerceOrderProduct represents the details of a product within an order.
# This type includes information such as the product pricing, quantity, and related attributes.
#
# The products data on an order is retrieved from the endpoint:
# https://api.bigcommerce.com/stores/{store_hash}/v2/orders/{order_id}/products
#
# More info can be found here:
# https://developer.bigcommerce.com/docs/rest-management/orders/order-products#list-order-products

type BigCommerceOrderProduct
  @dataType(name: "big_commerce_order_product", version: "2.0") {
  id: ID!
  is_refunded: Boolean
  name: String
  order_address_id: String
  order_id: String
  price_inc_tax: Currency
  product_id: String
  quantity: Int!
  quantity_refunded: Int
  quantity_shipped: Int
  sku: String
  type: String
  total_inc_tax: Currency
  wrapping_cost_inc_tax: Currency
}

enum TransactionEvent {
  purchase
  authorization
  capture
  refund
  void
  pending
  settled
}

enum TransactionStatus {
  ok
  error
}

# BigCommerceTransaction represents the details of a transaction associated with an order.
# This type includes information about the payment event, method, and status.
#
# This data is retrieved from the endpoint:
# https://api.bigcommerce.com/stores/{store_hash}/v3/orders/{order_id}/transactions
#
# More info can be found here:
# https://developer.bigcommerce.com/docs/rest-management/transactions#get-transactions
#
# Usage Notes:
# Depending on the payment method, different information will be available.
# Not all payment gateways return full card or fraud detail.

type BigCommerceTransaction
  @dataType(name: "big_commerce_transaction", version: "2.0") {
  id: ID!
  amount: Float!
  currency: String!
  date_created: DateTime
  event: TransactionEvent!
  gateway: String!
  order_id: String
  status: TransactionStatus
}

type OrderItem {
  order_product: BigCommerceOrderProduct
    @childIds(template: "{{.order_product_id}}")
}

# BigCommerceOrderShipment represents the details of a shipment within an order.
# This type includes information about the shipment, such as its ID, tracking details, and shipping address.
#
# This data is retrieved from the endpoint:
# https://api.bigcommerce.com/stores/{store_hash}/v2/orders/{order_id}/shipments
#
# More info can be found here:
# https://developer.bigcommerce.com/docs/rest-management/orders/order-shipments#get-order-shipments

type BigCommerceOrderShipment
  @dataType(name: "big_commerce_order_shipment", version: "2.0") {
  id: ID!
  customer_id: String
  date_created: DateTime
  generated_tracking_link: String
  items: [OrderItem]
  order_id: String
  shipping_address: AddressV2
  shipping_method: String
  shipping_provider: String
  tracking_carrier: String
  tracking_link: String
  tracking_number: String
}

# BigCommerceOrder represents the details of an order.
#
# This data is retrieved from the endpoint:
# https://api.bigcommerce.com/stores/{store_hash}/v2/orders/{order_id}
#
# The BigCommerce Order API allows you to fetch detailed information about a specific order by providing the order ID.
# This is a read-only endpoint, meaning it cannot be used to modify the order.
#
# Note: The `products`, `shipments`, and `transactions` fields are not included directly in the response from the
# order retrieval endpoint. Instead, they are populated through separate API requests. These additional API calls ensure
# that all relevant details about the order's contents, delivery, and financial transactions are available within the
# BigCommerceOrder type for both informational and action purposes.
#
# More info can be found here:
# https://developer.bigcommerce.com/docs/rest-management/orders#get-an-order

type BigCommerceOrder @dataType(name: "big_commerce_order", version: "2.0") {
  id: ID!
  base_handling_cost: Currency
  base_shipping_cost: Currency
  billing_address: AddressV2
  currency_code: String
  customer_id: String
  date_created: DateTime
  date_modified: DateTime
  date_shipped: DateTime
  external_order_id: String
  geoip_country: String
  payment_status: String
  products: [BigCommerceOrderProduct] @parentId(template: "{{.id}}")
  refunded_amount: Currency
  shipments: [BigCommerceOrderShipment] @parentId(template: "{{.id}}")
  staff_notes: String
  status: String
  status_id: String
  total_inc_tax: Currency
  transactions: [BigCommerceTransaction] @parentId(template: "{{.id}}")
}

# BigCommerceCustomer represents the details of a customer.
#
# This data is retrieved from the endpoint:
# https://api.bigcommerce.com/stores/{{store_hash}}/v3/customers?email:in={{urlquery $email}}
#
# The BigCommerce Customer API allows you to fetch detailed information about a specific customer
# by providing the email address. This is a read-only endpoint, meaning it cannot be used to modify the order.
#
# More info can be found here:
# https://developer.bigcommerce.com/docs/rest-management/customers#get-all-customers

type BigCommerceCustomer
  @dataType(name: "big_commerce_customer", version: "2.0") {
  id: ID!
  company: String
  customer_group_id: String
  date_created: DateTime
  date_modified: DateTime
  email: String
  first_name: String
  last_name: String
  notes: String
  orders: [BigCommerceOrder] @parentId(template: "{{.id}}")
  phone: String
}

type Query {
  customer: BigCommerceCustomer
}
